language: java
jdk:
  - oraclejdk8

notifications:
  email: false
  slack:
    rooms:
      - crusader8-dev:uk1gzRxbMrjf6BGLtCWl1Wfd#travis-ci
    on_success: change # default: always
    on_failure: always # default: always