language: java
jdk:
  - oraclejdk8

notifications:
  email: false
  slack:
    rooms:
      - crusader8-dev:BKBd1z5HXI3vpMZMjr2PE6oG#travis-ci
    on_success: change # default: always
    on_failure: always # default: always