language: java
jdk:
- oraclejdk8
notifications:
  email: false
  slack:
    rooms:
      secure: oPDt167VJFTic2G/OW8YW80byZe0nNZetRxi1nJHN0smFboTYnPvk9z0kRdGGk2zktgdKRxFj10U9uWrWN2DuQZhUOC+Rq58jXD+jwBC0wnBUk+SCzjzHVdUNkMicNaRYI+dQQy3TTGd9+rECXpLXwb4L3m2yRkh+PCSWp9Bb6AC126F3kgQSWiBD9OyLnWeM4arV49biLPtWO+vDYFf4WqH5AfHPkrliJ55eWKANFRFZE5sbEeFnfQyQIeJ8xi8PqaeQMsEJ3KR9YGRCxYPz0mSZdfMUcmd6yb1+KxJXUp843uBOVGalDIN3GOyuAtcMoBVYg4G4RCrWoUFQPJBRHYSeOtlLWqb+KfwvdtCndmlvi2+esSam5bGKcZkEaGKJMDU+U+iW2GJrdHvJQJ14pR0rgZS7w+bA4otT4cT2DuR793unoagOpBQMcLRDRS9Hbqv70fHqgNbtrQLJsH17P5XuUqCMvnlWc9+flf4J3yLM4pgZ1x6Zd++E2vHM2n8DAmh/SMOuFO3jBqzUlHz/vNiWFeWGwh8i29ABmVS/qMBtLWAmIlE02QdAkZusPfUevxGzJ/JMGtemSsw2Vy00IQiWcusFBxXHRWsM3RlBozRdJOtALwyEu3E3tbtUDfiKzLn/VFitj2xXPx3cXAqbBO4gmzBGvgv9Z+zG6x1B4A=
    on_success: change
    on_failure: always
addons:
  sonarqube:
    token:
      secure: Nu7+/lMt8SucdslH4K84xC7hGKvSB2H1TDW94kef3E+uzfuHhyYlAmRXfxMJiwAnvjvxe+v7yjgMU6SXyx9F1o9fRONYN9aGyYpwGWTkBkPN2ZKRLT9jqoBjaS88eL4fY1u5LxGikYiC7YHpgmCzj68mCR4ns2Ap6b3pGlkvYhsOVPi3flhdrD5zY2XpEAmxp9CseD12xGV1XVBbv9RIzYv96/Usnio3exAx5NaUZ/QHFrXUKMA17NiHesapJjcztZc5HvKKCHBlfDhS45F30lxLZl7ptAn9GJQZSNOjGCMNIvHQOCgja9KTbbJMQJ9AwT47dxKXmuOYuatStJHFqKM3z49sn/tTBeFEUGScLSobi5ikSRfbSHEngt/2Ujy5DaZTLG584k6DZE/10L+0Yv7Ae1oRp3LyFyMLZWlyzIovgRbf2acAj6WDYvRbTnphANFpkW/nzLmZldxm3qn+BD+5BLKMSVdgWtpsP2TzKvov86U1AXshsyecxtWSZFdh1qq1nnirWt1ysKnwvm6k/NOEJNdolzkLeF4FajUiMrZ60Wfbu6Y+U4zFEdIfLx1FwMgUJ25YhJ7PLmkR6HzPBHv5Ew5d6Lmwl0SgD8lYNIjwAjkIBE0T4us6JwIJ3lGXvQCouxAn6Ficzquo+PzHcejMh5irrzwp3Pd4RU8BbLI=
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
